# Generated by Django 3.0.7 on 2020-10-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200830_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='permission',
            field=models.CharField(default='일반', max_length=10),
        ),
    ]
